
	<footer>
		<p>Abstergo Sistema Datos Sistema de control de gastos</p>
		<hr />
		<details> 
              <Summary> Copyright 2016-2020. </summary> 
              <p> - Por Abstergo Datos. Todos los derechos reservados. </p> 
              <p>Todo el contenido y los gráficos de este sitio web son propiedad de la compañía Abstergo datos. </p> 
           </details>
	</footer>
	</div>
</body>
</html>